### ISSUE TITLE
Make high-level algorithm for code

### ISSUE THREAD

**Issue by jackchen0226** [jackchen0226/all-in-one-die#2]
Could be a flowchart, or pseudocode. Ideally the algorithm is simple enough to explain to a 5 year old and streamline the programming process.

**Comment by NFellows** [comment]
I made a high level flow chart to go along with some pseudo code I wrote. It's all super rough and I have some concerns about execution that we can go over in the meeting tonight 10/14 at 6:30 PM.

![411 Initial Flow Chart](https://user-images.githubusercontent.com/72576094/96053822-2ca50580-0e35-11eb-8416-8ad3390d1d8a.png)
[411 High Level Code.docx](https://github.com/jackchen0226/all-in-one-die/files/5381361/411.High.Level.Code.docx)

**Comment by devonmickels** [comment]
````
Int maxRoll = 20;
Float roll_threshold = 5;

Void loop()
    if (getTotalAcceleration() > roll_threshold)
        rollDice();

if(digitalRead(increaseButton))
    increaseMaxRoll();

if(digitalRead(decreaseButton))
    decreaseMaxRoll();

Float getTotalAcceleration()
    Float x, y, z = 0;
    for(1:10)
        x+= getXAcceleration();
        y+= getXAcceleration();
        z+= getXAcceleration();

    x/= 10; y/= 10; z/= 10;

    return sqrt(X*X + Y*Y + Z*Z);

Void rollDice()
    Int newRoll = Random.Range(0, maxroll);

    updateDisplay(newRoll);

Void updateDisplay(int num)
    //This function will depend on what type of display we have, and how we interface with it

Void increaseMaxRoll()
    maxRoll++;
    if(maxRoll > 20)
        maxRoll = 20;

Void decreaseMaxRoll()
    maxRoll--;
    if(maxRoll < 4)
        maxRoll = 4;

````

**Comment by devonmickels** [comment]
public enum Dice{
    4Sided,
    6Sided,
    8Sided,
    20Sided
}

**Comment by jackchen0226** [comment]
We could use enums, 

However it may be better to have a table +  max size of table for expandability and change the die index.

dies = [4, 6, 8, 10, 12, 20]
num_dies = 6
curr_die_index = 1; // d6

**Comment by jackchen0226** [comment]
```
POWER ON
PROMPT USER FOR DIE VALUE
	WAIT FOR INPUT 
		IF NO INPUT 
GO BACK TO PROMPT
		IF INPUT
			WAIT FOR SHAKE FOR ~5s
				CHECK FOR DIE SIZE
				IF SHAKEN
					PULL RANDOM NUM
						CHECK IF D20 WAS ROLLED
							PLAY CURSE IF ROLLED A 1
					DISPLAY VALUE
					ROLL SAME DIE?
						GO BACK TO WAIT FOR SHAKE
						POWER OFF TO QUIT
				IF NOT SHAKEN
					GO BACK TO PROMPT FOR DIE VALUE
					POWER OFF TO QUIT
```
Nicole's pseudocode
