### ISSUE TITLE
PCB Board Design

### ISSUE THREAD

**Issue by devonmickels** [jackchen0226/all-in-one-die#3]

**Comment by devonmickels** [comment]
Start here: https://www.sparkfun.com/tutorials/108

**Comment by devonmickels** [comment]
Makes use of a FT232R Chip to serve as a USB to UART/RS232 serial covnerter.

https://www.ftdichip.com/Products/ICs/FT232R.htm

**Comment by devonmickels** [comment]
FT232R Connections:

TXD - connects to ATMega328P port PD1(TXD)
RXD - connects to ATMega328P port PD0(RXD)

CTS - Not needed (Clear To Send) Used in handshaking.
RTS - Not needed (Request To Send) Used in handshaking.
DTR - (Data Terminal Ready) Connects to Auto Reset mechanism (connects through 100nF capacitor)
Auto-reset is a jumper that will enable auto-resetting of the chip upon uploading new code (RECOMMENDED)

TXLED - connects to RX LED
RXLED - connects to RX LED

Remove all jumpers as is? We are making a custom chip for the purpose of this dice. Doesn't really need customizability.

**Comment by devonmickels** [comment]
ATMega328P has to be flashable while soldered to the board.

Figure out how to flash the ATMega328P.

Uses the ICSP Port.
https://www.circuito.io/blog/atmega328p-bootloader/
https://www.instructables.com/Bootload-an-ATmega328/

**Comment by devonmickels** [comment]
![image](https://user-images.githubusercontent.com/5107773/96539760-b0edf300-1250-11eb-90de-84882f55cf34.png)

Board Schematic V1

Includes: Power, ATMega328P, ICSP port, GPIO Pins, Reset Button, MINI USB to Serial, Power Pins

Will add hardwired accelerometer in V2 when one has been chosen.

**Comment by devonmickels** [comment]
Added Accelerometer to board. Currently configured in: Normal Mode, +-6g Full-scale, Normal Power Mode

[Pinout](https://docs.google.com/spreadsheets/d/1-bTbX0FQvViED1a9R8AA79J1Jf53h3Y0m0HYpA_xxmE/edit?usp=sharing)

Questions:
We don't need open GPIO pins for anything? I'm adding dedicated pins to drive the LCD display and including the accelerometer on the board. There's no additional gpio pinout needed? Do we need a timer? Like oscillators on the board?

Additionally, we should order a ATMega328P to test basic board layout features, mainly the ICSP header and USB to Serial.

**Comment by devonmickels** [comment]
![image](https://user-images.githubusercontent.com/5107773/96808173-2c74af00-13cd-11eb-9bce-c6de82beec40.png)
Board Schematic V2

To-Do:
Add a speaker connection
Finalize dimensions and hole locations

**Comment by devonmickels** [comment]
![image](https://user-images.githubusercontent.com/5107773/97764827-2ec1c200-1acd-11eb-9078-c17d9c9e0c52.png)
Board Schematic V3

- Cleaned things up
- USB Power disconnected from main power
- USB power only powers the FT232R chip
- Speaker plug in
- Accelerometer pins exposed for testing purposes

TODO:
Add user inputs

**Comment by NFellows** [comment]
![IMG_8319](https://user-images.githubusercontent.com/72576094/101266455-e157f680-3703-11eb-83b9-da962c2b6fa1.jpg)
12/06/2020
Got parts soldered on. Some of the ceramic capacitors broke apart during assembly,  have backups on the way. The accelerometer will need to be attached off board because the actual ship can only be attached with heat.
