### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by jackchen0226** [jackchen0226/all-in-one-die#4]

**Comment by NFellows** [comment]
Possible Bill of Materials:

ATMega328P - https://www.microchip.com/wwwproducts/en/ATmega328p
OR
https://www.amazon.com/Fii-X3-Atmega328P-PU-Bundle-Sockets/dp/B018ZR3F7O/ref=sr_1_3?dchild=1&keywords=ATMega328P&qid=1602358508&sr=8-3

Battery - https://www.adafruit.com/product/727

Possible Accelerator:
https://www.mouser.com/ProductDetail/Analog-Devices/ADXL327BCPZ?qs=WIvQP4zGanhwHjckzi5o%2Fg%3D%3D

Screen - https://www.amazon.com/UCTRONICS-SSD1306-Self-Luminous-Display-Raspberry/dp/B072Q2X2LL

**Comment by devonmickels** [comment]
Final Bill of Materials: (WIP)

Breadboard Prototyping:
- [ ] ATMega328P [[Amazon](https://www.amazon.com/Fii-X3-Atmega328P-PU-Bundle-Sockets/dp/B018ZR3F7O/), [Microchip](https://www.microchip.com/wwwproducts/en/ATmega328p)]
- [ ] Accelerometer [[Adafruit](https://www.adafruit.com/product/2809?gclid=CjwKCAjw5p_8BRBUEiwAPpJO63mjiVLkubr_h_pRRTdRl0oy9-IgToR9G3K13dM386huOznbTZ9GsxoCieEQAvD_BwE)]
- [ ] LCD Screen [[Amazon](https://www.amazon.com/UCTRONICS-SSD1306-Self-Luminous-Display-Raspberry/dp/B072Q2X2LL)]
- [ ] Mini USB to Serial Converter [[Amazon](https://www.amazon.com/HiLetgo-FT232RL-Converter-Adapter-Breakout/dp/B00IJXZQ7C/ref=sr_1_1_sspa?dchild=1&keywords=FT232rl&qid=1602800742&s=electronics&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUE0WVRYVERTOVVMMCZlbmNyeXB0ZWRJZD1BMDQ2NDA4MDNIN1Q5STJXMEFOWEQmZW5jcnlwdGVkQWRJZD1BMDIzNjI4NjEwVDlaMVZYQ1dIVFkmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl)]

Final PCB: (Parts provided by PCBWay)
- [ ] ATMega328P (Processor) [Schematic Used](https://www.sparkfun.com/products/13448)
- [ ] FT232RL (USB to Serial Converter Chip)
- [ ] Accelerometer [Currently Using, might change](http://www.st.com/stonline/products/literature/ds/11020.pdf)

Final Construction:
- [ ] Assembled PCB
- [ ] LCD Screen [[Amazon](https://www.amazon.com/UCTRONICS-SSD1306-Self-Luminous-Display-Raspberry/dp/B072Q2X2LL)]
- [ ] 4xAA Battery Holder [[Amazon-Flat](https://www.amazon.com/LAMPVPATH-Battery-Holder-Leads-Wires/dp/B07T7MTRZX/), [Amazon-Fat](https://www.amazon.com/LAMPVPATH-Battery-Connector-Plastic-Housing/dp/B01MAXT00Q/)]

**Comment by jackchen0226** [comment]
For power

The ATMega328P can run on 1.8V minimum, but can run at 3.3V or 4.5-5.5V. Batteries (AA-AAAA) give 1.5V each, but lithium cells are also an option (about 3V).

The LCD screen requires 3.3-5V.

Accelerometer also works on 3,3V

**Comment by jackchen0226** [comment]
Added an initial Bill of Materials for the PCB design.

https://github.com/jackchen0226/all-in-one-die/wiki/Bill-of-Materials
