### ISSUE TITLE
Casing Desing

### ISSUE THREAD

**Issue by micromort** [jackchen0226/all-in-one-die#6]
![20201017_133533](https://user-images.githubusercontent.com/55212269/96353094-d1b21f00-107d-11eb-99b7-177fe6d1f6f8.jpg)
Super simple sketches. But I am a bit confused about some of the requirements. Can't the batteries and USB stuff be inside the casing? It should be handheld, and not needing to feed wires out of it. The casing will be in half and snap together (hopefully). Also for the screen/button(or dial) should they be full cut outs or how are we going to place them in? Please give feedback so new sketches/more in depth sketches can be made.

**Comment by devonmickels** [comment]
Rough Board Dimensions: 80mmx45mm. It could potentially get even smaller, but it shouldn't get any bigger than that. Also, I think the battery pack will be inside, like AAA's or something.

**Comment by micromort** [comment]
[Bottom_Half_draft_v1.pdf](https://github.com/jackchen0226/all-in-one-die/files/5471772/Bottom_Half_draft_v1.pdf)

**Comment by micromort** [comment]
![image](https://user-images.githubusercontent.com/55212269/97815641-630bbe80-1c44-11eb-967d-9b0b07bf37ba.png)

**Comment by micromort** [comment]
the pdf is the drawing with dimensions - super rough draft

**Comment by micromort** [comment]
![image](https://user-images.githubusercontent.com/55212269/97815939-93ecf300-1c46-11eb-98ff-598ce23bafc6.png)

**Comment by micromort** [comment]
Basic look into the bottom half grating for sound to come out of

**Comment by micromort** [comment]
[Bottom Half Draft v2.pdf](https://github.com/jackchen0226/all-in-one-die/files/5471811/Bottom.Half.Draft.v2.pdf)

**Comment by micromort** [comment]
[HOLDER_3.1.zip](https://github.com/jackchen0226/all-in-one-die/files/5613058/HOLDER_3.1.zip)
